# Generated by Django 4.0.5 on 2022-06-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0005_document_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=1000)),
                ('exhibit_text', models.TextField(blank=True)),
                ('items_in_exhibit', models.ManyToManyField(to='archive.archivedocument')),
            ],
        ),
    ]
