# Generated by Django 4.0.5 on 2022-06-19 00:41

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_image', stdimage.models.StdImageField(force_min_size=False, upload_to='photographs/', variations={'thumbnail': {'height': 300, 'width': 300}})),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
