# Generated by Django 4.0.5 on 2022-06-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('archive', '0002_archivedocument_remove_photograph_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedocument',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='photograph',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
