# Generated by Django 4.0.5 on 2022-06-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_alter_archivedocument_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.CharField(default='English', max_length=200),
            preserve_default=False,
        ),
    ]
