# Generated by Django 4.0.5 on 2022-07-26 18:07

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_document_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('creator', models.CharField(max_length=200)),
                ('photo_image', stdimage.models.StdImageField(force_min_size=False, upload_to='photographs/', variations={'thumbnail': {'height': 300, 'width': 300}})),
                ('associated_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.archivedocument')),
            ],
        ),
    ]
