# Generated by Django 4.0.5 on 2022-07-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_document_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedocument',
            name='creator',
            field=models.CharField(blank='True', max_length=50),
        ),
    ]
