# Generated by Django 4.0.5 on 2022-07-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_archivedocument_creator'),
        ('archive', '0006_associatedimage'),
    ]

    operations = [
    ]
