# Generated by Django 4.0.5 on 2022-07-26 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_merge_20220726_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('archivedocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archive.archivedocument')),
            ],
            bases=('archive.archivedocument',),
        ),
    ]
