# Generated by Django 4.0.5 on 2022-07-26 22:58

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='material',
            field=models.CharField(choices=[('other', 'Other'), ('plastic', 'Plastic'), ('ceramic', 'Ceramic'), ('glass', 'Glass')], default='glass', max_length=50),
        ),
        migrations.AlterField(
            model_name='archivedocument',
            name='photo_image',
            field=stdimage.models.StdImageField(force_min_size=False, null=True, upload_to='photographs/', variations={'thumbnail': {'height': 300, 'width': 300}}),
        ),
        migrations.AlterField(
            model_name='associatedimage',
            name='creator',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
