# Generated by Django 4.0.5 on 2022-07-26 23:03

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_artifact_material_alter_archivedocument_photo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='model3d',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivedocument',
            name='photo_image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='photographs/', variations={'thumbnail': {'height': 300, 'width': 300}}),
        ),
    ]
