# Generated by Django 4.0.5 on 2022-07-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_artifact_model3d_alter_archivedocument_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='model3d',
            field=models.URLField(blank='True', max_length=500),
        ),
    ]
