# Generated by Django 4.0.5 on 2022-07-30 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_alter_artifact_model3d'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarbucksMugs',
            fields=[
                ('archivedocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archive.archivedocument')),
                ('productionLocation', models.CharField(max_length=500)),
                ('displayedCity', models.CharField(max_length=500)),
                ('sizeOunces', models.IntegerField()),
                ('date', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=500)),
                ('shapeDescription', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('material', models.CharField(max_length=500)),
                ('productLink', models.URLField(max_length=500)),
                ('link3DModel', models.URLField(blank='True', max_length=500)),
            ],
            bases=('archive.archivedocument',),
        ),
    ]
