# Generated by Django 4.0.5 on 2022-08-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_alter_artifact_model3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='material',
            field=models.CharField(choices=[('other', 'Other'), ('plastic', 'Plastic'), ('ceramic', 'Ceramic'), ('glass', 'Glass'), ('metal', 'Metal')], default='glass', max_length=50),
        ),
    ]
