# Generated by Django 4.0.5 on 2022-08-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_alter_artifact_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='transcription',
        ),
        migrations.AddField(
            model_name='document',
            name='contributor_names',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='form',
            field=models.CharField(choices=[('electronic', 'Electronic'), ('other', 'Other')], default='electronic', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='genre',
            field=models.CharField(choices=[('website', 'Website'), ('other', 'Other')], default='website', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='location_published',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='online_format',
            field=models.CharField(choices=[('web page', 'Web Page'), ('other', 'Other')], default='web page', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='pdf',
            field=models.FileField(default='N/A', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='document',
            name='source_URL',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='subject_headings',
            field=models.TextField(blank=True),
        ),
    ]
