# Generated by Django 4.0.5 on 2022-07-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_starbucksmugs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StarbucksMugs',
            new_name='StarbucksMug',
        ),
    ]
