# Generated by Django 4.0.5 on 2022-08-04 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_remove_document_transcription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='pdf',
            new_name='PDF',
        ),
    ]
