# Generated by Django 4.0.5 on 2022-08-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_rename_starbucksmugs_starbucksmug'),
    ]

    operations = [
        migrations.AddField(
            model_name='starbucksmug',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('brown', 'Brown'), ('multi', 'Multi'), ('other', 'Other')], default='multi', max_length=500),
        ),
        migrations.AddField(
            model_name='starbucksmug',
            name='season',
            field=models.CharField(choices=[('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('spring', 'Spring'), ('none', 'None')], default='none', max_length=500),
        ),
    ]
