# Generated by Django 4.0.5 on 2023-08-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_audiorecording'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivedocument',
            old_name='creator',
            new_name='artist',
        ),
    ]
