# Generated by Django 4.0.5 on 2023-08-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_audiorecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='designer',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='artifact',
            name='installed_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='artifact',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='artifact',
            name='sculptor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='material',
            field=models.CharField(choices=[('other', 'Other'), ('plastic', 'Plastic'), ('ceramic', 'Ceramic'), ('glass', 'Glass'), ('metal', 'Metal')], default='metal', max_length=50),
        ),
    ]
