# Generated by Django 4.0.5 on 2022-08-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_rename_pdf_document_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
