# Generated by Django 4.0.5 on 2023-08-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_remove_document_archivedocument_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('archivedocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archive.archivedocument')),
                ('language', models.CharField(max_length=200)),
                ('speaker', models.CharField(blank=True, max_length=200)),
                ('recording_date', models.DateField(auto_now=True)),
                ('audio_file', models.FileField(null=True, upload_to='sounds/')),
            ],
            bases=('archive.archivedocument',),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('archivedocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archive.archivedocument')),
                ('language', models.CharField(max_length=200)),
                ('transcription', models.TextField(blank=True)),
            ],
            bases=('archive.archivedocument',),
        ),
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('archivedocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archive.archivedocument')),
                ('photo_type', models.CharField(choices=[('glass', 'Glass Slide'), ('35mm', '35mm Slide'), ('polaroid', 'Polaroid'), ('print', 'Printed Photo'), ('digital', 'Born Digital Photo')], max_length=20)),
            ],
            bases=('archive.archivedocument',),
        ),
        migrations.CreateModel(
            name='Sculpture',
            fields=[
                ('archivedocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archive.archivedocument')),
                ('material', models.CharField(choices=[('other', 'Other'), ('plastic', 'Plastic'), ('ceramic', 'Ceramic'), ('glass', 'Glass'), ('metal', 'Metal')], default='metal', max_length=50)),
                ('model3d', models.URLField(blank='True', max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('installed_year', models.CharField(blank=True, max_length=4)),
                ('designer', models.CharField(blank=True, max_length=20)),
                ('sculptor', models.CharField(blank=True, max_length=20)),
            ],
            bases=('archive.archivedocument',),
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='installed_year',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='location',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='sculptor',
        ),
        migrations.AlterField(
            model_name='artifact',
            name='material',
            field=models.CharField(choices=[('other', 'Other'), ('plastic', 'Plastic'), ('ceramic', 'Ceramic'), ('glass', 'Glass'), ('metal', 'Metal')], default='glass', max_length=50),
        ),
    ]
