# Generated by Django 4.0.5 on 2022-08-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_starbucksmug_holiday_alter_starbucksmug_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starbucksmug',
            name='displayedCity',
        ),
        migrations.AddField(
            model_name='starbucksmug',
            name='displayedLocation',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
