# Generated by Django 4.0.5 on 2023-08-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_alter_audiorecording_audio_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivedocument',
            old_name='artist',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='audiorecording',
            old_name='speaker',
            new_name='artist',
        ),
    ]
