# Generated by Django 4.0.5 on 2023-08-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_audiorecording_document_photograph_sculpture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sculpture',
            name='model3d',
        ),
    ]
