# Generated by Django 4.0.5 on 2022-08-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_remove_starbucksmug_displayedcity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starbucksmug',
            name='date',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
