# Generated by Django 4.0.5 on 2023-08-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0017_remove_sculpture_model3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='sculpture',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sculpture',
            name='height',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sculpture',
            name='length',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sculpture',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sculpture',
            name='width',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='material',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
