# Generated by Django 4.0.5 on 2023-08-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0018_sculpture_color_sculpture_height_sculpture_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sculpture',
            name='installed_year',
            field=models.IntegerField(blank=True, max_length=4),
        ),
    ]
