# Generated by Django 4.0.5 on 2023-08-03 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0018_associatedimage_associated_doc1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenreToRecords',
            new_name='GenreToRecord',
        ),
    ]
