# Generated by Django 4.0.5 on 2023-08-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0019_rename_genretorecords_genretorecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='genre',
            field=models.ManyToManyField(to='archive.genre'),
        ),
    ]
