# Generated by Django 4.0.5 on 2023-08-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0020_alter_sculpture_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sculpture',
            name='installed_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
