# Generated by Django 4.0.5 on 2023-08-03 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0020_audiorecording_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genretorecord',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='genretorecord',
            name='record',
        ),
    ]
