# Generated by Django 4.0.5 on 2023-08-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0021_alter_sculpture_installed_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sculpture',
            name='installed_year',
            field=models.CharField(blank=True, default='unknown', max_length=4),
        ),
    ]
