# Generated by Django 4.0.5 on 2023-08-03 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0021_remove_genretorecord_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genretorecord',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.genre'),
        ),
        migrations.AddField(
            model_name='genretorecord',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.audiorecording'),
        ),
    ]
