# Generated by Django 4.0.5 on 2023-08-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0022_alter_sculpture_installed_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sculpture',
            name='height',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='length',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='weight',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='width',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
