# Generated by Django 4.0.5 on 2023-08-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0022_genretorecord_genre_genretorecord_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='record_label',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
