# Generated by Django 4.0.5 on 2023-08-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0023_alter_sculpture_height_alter_sculpture_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sculpture',
            name='installed_year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
