# Generated by Django 4.0.5 on 2023-08-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0023_audiorecording_record_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecording',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='archive.genre'),
        ),
    ]
